title: Baie Vivante er Solidaire
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: Baie Vivante er Solidaire
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
keep_files:
- images
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
    imagesdir: /images
