= Reunion
:showtitle:
:page-navtitle: Reunion
:page-excerpt: Excerpt goes here.
:page-root: ../../../


= h1
== h2

- Edgar Allen Poe
- Sheri S. Tepper
- Bill Bryson

. Protons
. Electrons
. Neutrons

=== h3

* level 1
** level 2
*** level 3
**** level 4
***** level 5
* level 1

==== h4

[cols=2*]
|===
|Firefox
|Web Browser

|Ruby
|Programming Language

|TorqueBox
|Application Server
|===

===== h5

|===
|Cell in column 1, row 1 |Cell in column 2, row 1 |Cell in column 3, row 1 |Cell in column 4, row 1

4*|Same cell content in columns 1, 2, 3 and 4

4+|Content in a single cell that spans columns 1, 2, 3 and 4

|Cell in column 1, row 4
|Cell in column 2, row 4
|Cell in column 3, row 4
|Cell in column 4, row 4

|Cell in column 1, row 5
2.2+| Marge column 1, 2 and Row 5, 6
|Cell in column 4, row 5

|Cell in column 1, row 6
|Cell in column 4, row 6
|===


DES DIAGRAMMES : https://plantuml.com/fr/



[plantuml, format="png", id="myId"]
....
@startuml
:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
  A note can also
  be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml
....



[plantuml, format="png", id="myId2"]
....
@startuml
participant Participant as Foo
actor       Actor       as Foo1
boundary    Boundary    as Foo2
control     Control     as Foo3
entity      Entity      as Foo4
database    Database    as Foo5
collections Collections as Foo6
queue       Queue       as Foo7
Foo -> Foo1 : To actor 
Foo -> Foo2 : To boundary
Foo -> Foo3 : To control
Foo -> Foo4 : To entity
Foo -> Foo5 : To database
Foo -> Foo6 : To collections
Foo -> Foo7: To queue
@enduml

....


[plantuml, format="png", id="myId3"]
....
@startuml
' Split into 4 pages
page 2x2
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

class BaseClass

namespace net.dummy #DDDDDD {
    .BaseClass <|-- Person
    Meeting o-- Person

    .BaseClass <|- Meeting

}

namespace net.foo {
  net.dummy.Person  <|- Person
  .BaseClass <|-- Person

  net.dummy.Meeting o-- Person
}

BaseClass <|-- net.unused.Person
@enduml
....

[plantuml, format="png", id="myId4"]
....
@startuml
title Point two queries to same activity\nwith `goto`
start
if (Test Question?) then (yes)
'space label only for alignment
label sp_lab0
label sp_lab1
'real label
label lab
:shared;
else (no)
if (Second Test Question?) then (yes)
label sp_lab2
goto sp_lab1
else
:nonShared;
endif
endif
:merge;
@enduml
....

[plantuml, format="png", id="myId5"]
....
@startmindmap
+ OS
++ Ubuntu
+++ Linux Mint
+++ Kubuntu
+++ Lubuntu
+++ KDE Neon
++ LMDE
++ SolydXK
++ SteamOS
++ Raspbian
-- Windows 95
-- Windows 98
-- Windows NT
--- Windows 8
--- Windows 10
@endmindmap
....



